baseURL = "https://bingzw.github.io/"
languageCode = 'en-us'
theme = 'anubis2'
title = 'Bingz Learning Blog'
publishDir = "docs"

[author]
name = "Bing Wang"
email  = "bingwang8878@gamil.com"
# location = "Singapore"

[menu]
[[menu.main]]
name = "Home"
pageRef = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Archive"
url = "/posts/"
weight = 4

[params]
readMore = false # true | false; Showing readmore link in the list of posts; default: false
readNextPosts = 3 # Number of posts to show in the "Read Next" section; default: 3
colorTheme = "auto" # "auto" | "light" | "dark"; default: "auto"
colorThemeSwitcher = true # true | false; Showing color theme switcher in top of the site; default: false
toc = true # true | false; Showing table of contents in the post; default: true
math = true # true | false; Enable MathJax; default: false; You can enable MathJax in the post by adding math: true in a post's metadata section.

# check more social icons at https://github.com/Junyi-99/hugo-theme-anubis2/wiki/Social-Icons
social = [
    { id="github", name="bingzw" },
    { id="linkedin", url="https://www.linkedin.com/in/bingzw/" },
]

# rssIcon = true # true | false; Showing RSS icon; default: true

[taxonomies]
tag = "tags" # This allows you to use the "tags" in your markdown metadata

[markup.goldmark.renderer]
unsafe = true # true | false; Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Highlight.js style
